// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgE-L9AEomBlPAysIlqnaJI_PFt77d0x4',
    appId: '1:46076461545:web:ae5059a8d7b7891ba38b78',
    messagingSenderId: '46076461545',
    projectId: 'hostbooks-51ae6',
    authDomain: 'hostbooks-51ae6.firebaseapp.com',
    storageBucket: 'hostbooks-51ae6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDjO3Pbu9zdBA8LtacKDjrhKLD_tLWjyc',
    appId: '1:46076461545:android:5d02045d9a4a911fa38b78',
    messagingSenderId: '46076461545',
    projectId: 'hostbooks-51ae6',
    storageBucket: 'hostbooks-51ae6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnLWyFi69E0nwxYPZq6IATZA37DCAtIUk',
    appId: '1:46076461545:ios:46d71dfd9f4002b6a38b78',
    messagingSenderId: '46076461545',
    projectId: 'hostbooks-51ae6',
    storageBucket: 'hostbooks-51ae6.appspot.com',
    iosClientId: '46076461545-e2cbjum705mfnu810sjl3dr5dhl84eti.apps.googleusercontent.com',
    iosBundleId: 'com.example.oonzoo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnLWyFi69E0nwxYPZq6IATZA37DCAtIUk',
    appId: '1:46076461545:ios:ca974b9f52e8dd9ea38b78',
    messagingSenderId: '46076461545',
    projectId: 'hostbooks-51ae6',
    storageBucket: 'hostbooks-51ae6.appspot.com',
    iosClientId: '46076461545-rgi6crsiim2bcfvp183qmjuie3rmnogq.apps.googleusercontent.com',
    iosBundleId: 'com.example.oonzoo.RunnerTests',
  );
}
